name: Build and create release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Publish project
        run: dotnet publish --no-restore -c Release -r win
      - name: Run tests
        run: dotnet test --no-build --verbosity normal
      - name: Zip build
        uses: vimtor/action-zip@v1
        with:
          files: "AssemblyReflector/bin/Release/net472/win/publish/"
          dest: "Build.zip"
          recursive: true
      - name: Delete old release
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            Build.zip
            LICENSE
          prerelease: true
          tag: latest
          release: "Development build"